### PR TITLE
Allow for dual numbers in polyfc solving

### PR DESCRIPTION
**Pull request by aarmey**
These changes should allow for autodiff through the polyfc solver. There were just some type issues preventing it. I've added a test to check that ForwardDiff works with polyfc calls.

### CODE REVIEW

**Comment by cyrillustan** [comment]
I'm wondering what's the difference between using promote_type() and simply declare/convert everything as/into real numbers. I assume ForwardDiff is capable of handling the rest (e.g. dual number conversion) once everything is continuous?

**Comment by aarmey** [comment]
Dual numbers are *two* float values stored as one variable, so you can go Float -> Dual but not the other way around. Promote_type() uses the Dual type when present, or the Float type when the input is just floats. If you convert down to a float you lose the derivative information. This is better than always using Dual types because the Dual type is slower.

**Comment by aarmey** [comment]
Maybe these notes help? https://mitmath.github.io/18337/lecture8/automatic_differentiation

**Comment by cyrillustan** [comment]
I see your point. Alright, I’ll change the polyfc_ActV code accordingly and merge. I assume this change will also make L0 and f regression work?

The reason I have a separate function, polyfc_ActV, is that I’m thinking of adding parallel computing, which will help “translation” go faster. I haven’t figured out the best way to do that yet. I should probably open a new branch for that

**Comment by aarmey** [comment]
Yep, this makes FcgR.jl always work with forwarddiff.

Parallel solving makes sense. This autodiff should also speed up the "translation", as the fitting version was spending most time doing finite differencing.

**Comment by aarmey** [comment]
(P.S. The code in Julia will also probably be faster just because of the language change.)

**Pull request merged**
